applications/departamentos/urls.py
from django.contrib import admin
from django.urls import path

from . import views
    
app_name = 'departamento_app'

urlpatterns = [
    path('lista-dep/', views.DepartamentoListView.as_view(), name='departamento_list'),
    path('new-departamento/', views.NewDepartamentoView.as_view(), name='nuevo_departamento'),
]

applications/personas/urls.py
from django.contrib import admin
from django.urls import path

from . import views
    
app_name = 'persona_app'

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar_todos_empleados/', views.ListAllEmpleados.as_view(),name='empleados_all'),
    path('listar_by_area/<shortname>/', views.ListByArea.as_view(), name='empleados_area'),
    path('listar_by_trabajo/<shortname>/', views.ListByTrabajo.as_view()),
    path('buscar_empleado/', views.ListEmpleadosByKword.as_view()),
    path('listar_habilidades_e/', views.ListHabilidades.as_view()),
    path('ver_empleado/<pk>/', views.EmpleadoDetailView.as_view(), name="empleado_detalle"),
    path('crear_empleado/', views.EmpleadoCreateView.as_view(), name="empleado_crear"),    
    path('success', views.SuccessView.as_view(), name='correcto'),
    path('unsuccess', views.UnsuccessView.as_view(), name='incorrecto'),
    path('update_empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('borrar_empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='borrar_empleado'),
]

empleados/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static    

urlpatterns = [
    path('admin/', admin.site.urls),
    #URLs de las Applications
    path('', include('applications.departamentos.urls')),
    path('', include('applications.personas.urls')),
    path('', include('applications.inicio.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/departamentos/models.py
from django.db import models
from unittest.util import _MAX_LENGTH

# Create your models here.

class Departamento (models.Model):
    name = models.CharField('Nombre', max_length=50, blank=True)
    shortName = models.CharField('Nombre Corto', max_length=15, unique=True)
    anulate = models.BooleanField('Anulado', default=False)
    
    class Meta:
        verbose_name = 'Mi departamento' 
        verbose_name_plural = 'Mis departamentos'
        ordering = ['shortName', 'name']
        unique_together = ('name', 'shortName')
        
    def __str__ (self):
        return str(self.id) + ' - ' + 'Nombre: ' + self.name + ', ' + 'Nombre Corto:' + self.shortName

applications/departamentos/forms.py
from django import forms

class NewDepartamentoForm (forms.Form):
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=150)
    departamento = forms.CharField(max_length=80)
    shortname = departamento = forms.CharField(max_length=20)
    
                                 

applications/departamentos/views.py
from django.shortcuts import render

from django.urls import reverse_lazy
from django.views.generic.edit import FormView
from django.views.generic import ListView

from .forms import NewDepartamentoForm 

from applications.personas.models import Empleado
from .models import Departamento

# Create your views here.


class DepartamentoListView(ListView):
    model = Departamento
    template_name = "departamentos/lista.html"
    context_object_name = 'departamentos'


class NewDepartamentoView  (FormView):
    template_name = 'departamentos/new_departamento.html'
    form_class = NewDepartamentoForm
    success_url = '/'
    
    def form_valid(self, form):
        depart = Departamento(
            name = form.cleaned_data['departamento'],
            shortName = form.cleaned_data['shortname'],
        )
        depart.save()
        
        nombre = form.cleaned_data['nombre']
        apellido = form.cleaned_data['apellidos']
        Empleado.objects.create(
            firstName = nombre,
            lastName = apellido,
            job = 1,
            departamento = depart
        )
        return super(NewDepartamentoView, self).form_valid(form)
    
    

templates/departamentos/lista.html
{% extends 'base.html' %}

{% block title %}
    Lista Departamentos
{% endblock title %}

    
{% block content %}
    {% include 'includes/header.html' %}
    
    <div class="grid-container">
        <div class="grid-x">
            <h1 class="cell">Lista Departamentos</h1>
            <div class="cell">
                <table>
                    <tbody>
                           
                            {% for departamento in departamentos  %}
                                <tr>
                                    <td>{{ departamento.name }}</td>
                                    <td>{{ departamento.shortName }}</td>
                                    <td>
                                        <td><a class="button warning" href="{% url 'persona_app:empleados_area' departamento.shortName %}">Ver Empleados</a></td>
                                    </td>
                                </tr>
                            {% endfor %}
                                
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock content %}
    

templates/departamentos/new_departamento.html
{% extends 'base.html' %}

{% block title %}Nuevo Departamento{% endblock title %}

    
{% block content %}
    {% include 'includes/header.html' %}

	<div class="grid-container">
		<div class="grid-x">
			<h1 class="cell">Nuevo Departamento</h1>

			<div class="cell">
			<form class="cell grid-x grid-margin-x" method='POST' enctype="multipart/form-data" > {% csrf_token %} 
				<h2 class="cell large-12">Datos Empleado</h2>
				<div class="cell large-6">
					<label>
						<label>Nombre: {{ form.nombre }}</label>
					</label>
				</div>
				<div class="cell large-6">
					<label>
						<label>Apellidos: {{ form.apellidos }}</label>
					</label>
				</div>

				<h2 class="cell large-12">Datos Departamento</h2>
				<div class="cell large-6">
					<label>
						<label>Departamento: {{ form.departamento }}</label>
					</label>
				</div>
				<div class="cell large-6">
					<label>
						<label>Nombre Corto: {{ form.shortname }}</label>
					</label>
				</div>

				<div class="cell large-12">
					<button class="button success" type ="submit">Agregar</button>
				</div>
			</form>
			</div>
		</div>
	</div>

{% endblock content %}