applications/departamentos/urls.py
from django.contrib import admin
from django.urls import path

from . import views
    
app_name = 'departamento_app'

urlpatterns = [
    path('lista-dep/', views.DepartamentoListView.as_view(), name='departamento_list'),
    path('new-departamento/', views.NewDepartamentoView.as_view(), name='nuevo_departamento'),
]

applications/personas/urls.py
from django.contrib import admin
from django.urls import path

from . import views
    
app_name = 'persona_app'

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar_todos_empleados/', views.ListAllEmpleados.as_view(),name='empleados_all'),
    path('listar_by_area/<shortname>/', views.ListByArea.as_view(), name='empleados_area'),
    path('listar_by_trabajo/<shortname>/', views.ListByTrabajo.as_view()),
    path('buscar_empleado/', views.ListEmpleadosByKword.as_view()),
    path('listar_habilidades_e/', views.ListHabilidades.as_view()),
    path('ver_empleado/<pk>/', views.EmpleadoDetailView.as_view(), name="empleado_detalle"),
    path('crear_empleado/', views.EmpleadoCreateView.as_view(), name="empleado_crear"),    
    path('success', views.SuccessView.as_view(), name='correcto'),
    path('unsuccess', views.UnsuccessView.as_view(), name='incorrecto'),
    path('update_empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('borrar_empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='borrar_empleado'),
]

empleados/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static    

urlpatterns = [
    path('admin/', admin.site.urls),
    #URLs de las Applications
    path('', include('applications.departamentos.urls')),
    path('', include('applications.personas.urls')),
    path('', include('applications.inicio.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/header.html
<div class="top-bar">
    <div class="top-bar-left">
      <ul class="dropdown menu" data-dropdown-menu>
        <li class="menu-text">Empleados</li>
        <li><a href="{% url 'persona_app:empleados_all' %}">Listar</a></li>
        <li><a href="{% url 'departamento_app:departamento_list' %}">Departamentos</a></li>
        <li><a href="{% url 'departamento_app:nuevo_departamento' %}">NuevoDep</a></li>
      </ul>
    </div>
    <div class="top-bar-right">
      <ul class="menu">
        <li><a href="{% url 'persona_app:empleado_crear' %}" type="button" class="button">Registrar Nuevo</a></li>
        <li><input type="search" placeholder="Buscar Empleado"></li>
      </ul>
    </div>
  </div>