applications/personas/urls.py
from django.contrib import admin
from django.urls import path

from . import views
    
app_name = 'persona_app'

urlpatterns = [
    path('', views.InicioView.as_view(), name='inicio'),
    path('listar_todos_empleados/', views.ListAllEmpleados.as_view(),name='empleados_all'),
    path('listar_by_area/<shortname>/', views.ListByArea.as_view(), name='empleados_area'),
    path('listar_by_trabajo/<shortname>/', views.ListByTrabajo.as_view()),
    path('buscar_empleado/', views.ListEmpleadosByKword.as_view()),
    path('listar_habilidades_e/', views.ListHabilidades.as_view()),
    path('ver_empleado/<pk>/', views.EmpleadoDetailView.as_view(), name="empleado_detalle"),
    path('crear_empleado/', views.EmpleadoCreateView.as_view(), name="empleado_crear"),    
    path('success', views.SuccessView.as_view(), name='correcto'),
    path('unsuccess', views.UnsuccessView.as_view(), name='incorrecto'),
    path('update_empleado/<pk>/', views.EmpleadoUpdateView.as_view(), name='modificar_empleado'),
    path('borrar_empleado/<pk>/', views.EmpleadoDeleteView.as_view(), name='borrar_empleado'),
]

empleados/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static    

urlpatterns = [
    path('admin/', admin.site.urls),
    #URLs de las Applications
    path('', include('applications.departamentos.urls')),
    path('', include('applications.personas.urls')),
    path('', include('applications.inicio.urls'))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

applications/personas/models.py
from django.db import models
from applications.departamentos.models import Departamento
# Create your models here.
from ckeditor.fields import RichTextField

class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)
    
    class Meta:
        verbose_name = 'Habilidad'
        verbose_name_plural = 'Habilidades Empleados'
        
    def __str__ (self):
        return str(self.id) + ', ' + self.habilidad + '#'
    

class Empleado(models.Model):
    """ Modelo  para tabla empleado """
    JOB_CHOICES = (
        ('0', 'Contador'),
        ('1', 'Administrador'),
        ('2', 'Economista'),
        ('4', 'Otro')
        )
    firstName = models.CharField('Nombre', max_length=60)
    lastName = models.CharField('Apellidos', max_length=200)
    fullName = models.CharField(
        'Nombres Completos, ',
        blank = True,
        max_length=260
    )
    job = models.CharField('Trabajo', max_length=50, choices=JOB_CHOICES)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    foto = models.ImageField(upload_to='empleados', blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidades)
    hojaVida = RichTextField()

        
    class Meta:
        verbose_name = 'El empleado'
        verbose_name_plural = 'Los empleados'
        ordering = ['lastName', 'firstName']
        unique_together = ('firstName', 'lastName')

    def __str__ (self):
        return str(self.id) + ' - ' + 'Nombre: ' + self.firstName+ ', ' + 'Apellidos:' + self.lastName

applications/personas/forms.py
from django import forms
from .models import Empleado, Habilidades

class EmpleadoForm(forms.ModelForm):

    class Meta:
        model = Empleado
        fields = (
            'firstName',
            'lastName',
            'job',
            'departamento',
            'foto',
            'habilidades',
            )
        widgets = {
            'habilidades': forms.CheckboxSelectMultiple()
        }

applications/personas/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView
)
from django.http import HttpResponseRedirect
from .models import Empleado    
from django.views.generic.edit import CreateView
# Forms
from .forms import EmpleadoForm
# Create your views here.

class InicioView (TemplateView):
    ''' Vista que carga la página de inicio '''
    template_name = 'inicio.html'

# 1 - Listar todos los empleados de la empresa
class ListAllEmpleados (ListView):
    template_name = 'personas/list_all.html'
    paginate_by = 4 # 5 - Paginaciión de un listado
    ordering = 'lastName'
    context_object_name = 'empleados'
    
    def get_queryset (self):
        palabraClave = self.request.GET.get('kword','')
        lista = Empleado.objects.filter(
            fullName__icontains = palabraClave 
        )
        return lista

# 2 - Listar empleados de un área
class ListByArea (ListView):
    template_name = 'personas/list_all.html'
    context_object_name = 'empleados'
    
    def get_queryset (self):
        area = self.kwargs['shortname']
        lista = Empleado.objects.filter(
            departamento__shortName = area 
        )
        return lista


# 3 - Listar empleados por trabajo
class ListByTrabajo (ListView):
    template_name = 'personas/list_all.html'
    contect_object_name = 'listaArea'
    
    def get_queryset (self):
        trabajo = smelf.kwargs['shortname']
        
        lista = Empleado.objects.filter(
            job = trabajo
        )
        
        if not lista:
            lista = Empleado.JOB_CHOICES
            
        return lista

# 4 - Listar empleados por palabra clave
class ListEmpleadosByKword (ListView):
    """ Lista empleados por palabra clave """
    template_name = 'personas/persona_by_kword.html'
    context_object_name = 'empleados'
    
    def get_queryset (self):
        palabraClave = self.request.GET.get('kword','')
        lista = Empleado.objects.filter(
            firstName = palabraClave 
        )
        return lista
    
# 5 - Listar habiliades de un empleado
class ListHabilidades (ListView):
    template_name = 'personas/habilidades.html'
    context_object_name = 'habilidades'

    def get_queryset(self):
        idEmpleado = self.request.GET.get('idEmpleado','')
        if idEmpleado:
            empleado = Empleado.objects.get(id=idEmpleado)
            return empleado.habilidades.all()
        else:
            return []


class EmpleadoDetailView (DetailView):
    model = Empleado
    template_name = 'personas/detail_empleado.html'
    context_object_name = 'empleados'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['titulo'] = self.object.fullName
        
        return context


class SuccessView (TemplateView):
    template_name = 'personas/success.html'

class UnsuccessView (TemplateView):
    template_name = 'personas/unsuccess.html'
    
class EmpleadoCreateView (CreateView):
    template_name = 'personas/add.html'
    model = Empleado
    form_class = EmpleadoForm

    success_url = reverse_lazy('persona_app:empleado_crear')
    
    def form_valid(self, form):
        empleado = form.save(commit=False)
        empleado.fullName = empleado.firstName + ' '+ empleado.lastName
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)
    

class EmpleadoUpdateView (UpdateView):
    template_name = 'personas/update.html'
    model = Empleado
    fields = ['firstName', 'lastName', 'job', 'departamento', 'habilidades']
    
    success_url = reverse_lazy('persona_app:empleados_all')
        
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        print (request.POST['firstName'])
        return super().post (request, *args, **kwargs)
    
    def form_valid(self, form):
        return super(EmpleadoUpdateView, self).form_valid(form)
    

class EmpleadoDeleteView (DeleteView):
    model = Empleado
    template_name = 'personas/delete.html'
    success_url = reverse_lazy('persona_app:empleados_all')
    unsuccess_url = '/unsuccess'
    
    def form_valid(self, form):
        success_url = self.get_success_url()
        object = self.get_object()
        lFirstName = object.firstName
        lista = Empleado.objects.filter(
            firstName = lFirstName 
        )
        if lista.count() > 1:
            return HttpResponseRedirect(self.unsuccess_url)
        else:
            self.object.delete()
            return HttpResponseRedirect(success_url)
        
                
                

templates/personas/add.html
{% extends 'base.html' %}

{% block title %}Crear Empleado{% endblock title %}

    
{% block content %}
    {% include 'includes/header.html' %}

	<div class="grid-container">
		<div class="grid-x">
			<h1 class="cell">Crear Empleado</h1>

			<div class="cell">
			<form class="cell grid-x grid-margin-x" method='POST' enctype="multipart/form-data" > {% csrf_token %} 
				<div class="cell large-6">
					<label>
						<label>Nombre: {{ form.firstName }}</label>
					</label>
				</div>
				<div class="cell large-6">
					<label>
						<label>Apellidos: {{ form.lastName }}</label>
					</label>
				</div>
				<div class="cell large-6">
					<label>
						<label>Trabajo: {{ form.job }}</label>
					</label>
				</div>
				<div class="cell large-6">
					<label>
						<label>Departamento: {{ form.departamento }}</label>
					</label>
				</div>
				<div class="cell large-12">
					<label>
						<label>Habilidades: {{ form.habilidades }}</label>
					</label>
				</div>
				<div class="cell large-12">
					<label>
						<label>Foto: {{ form.foto }}</label>
					</label>
				</div>
				<div class="cell large-12">
					<button class="button success" type ="submit">Agregar</button>
				</div>
			</form>
			</div>
		</div>
	</div>

{% endblock content %}

templates/personas/delete.html
{% extends 'base.html' %}

{% block title %}Borrar Empleado{% endblock title %}

    
{% block content %}
    {% include 'includes/header.html' %}

	<div class="grid-container">
	<div class="grid-x">
		<h1 class="cell">Borrar Empleado {{ object.firstName }}</h1>

		<form class="cell" method='POST'> {% csrf_token %}
				<button class="button success" type ="submit">Confirmar</button>		
		</form>
	</div>
	</div>

{% endblock content %}

templates/personas/detail_empleado.html
{% extends 'base.html' %}

{% load static %}

{% block title %}
    {{ object.full_name }}
{% endblock title %}
    
{% block content %}

    {% include 'includes/header.html' %}

    <div class="grid-container">
        <div class="grid-x align-center">
            <div class="card cell larga-4" style="width: 300px; margin-top:10px;">
                <div class="card-divider">
                    Empleado {{ titulo }}
                </div>
                {% if empleados.foto %}
                    <img src="{{ empleados.foto.url }}">
                {% else %}
                    <img src="{% static '/img/img2.jpg' %}">
                {% endif %}
                <div class="card-section">
                    <h4>Datos</h4>
                    
                    <label class="cell large-12">
                        Nombre: {{ empleados.firstName }}
                    </label>
                    <label class="cell large-12">
                        Apellidos: {{ empleados.lastName }}
                    </label>
                    <label class="cell large-12">
                        Trabajo: {{ empleados.get_job_display }}
                    </label>
                    <label class="cell large-12">
                        Departamento: {{ empleados.departamento.shortName }}
                    </label>                              
                    <p><span class="cell large-12">Habilidades:</span>
                        <ul class="vertical menu">
                            {% for h in empleados.habilidades.all %}
                                <li>{{ h.habilidad }}</li>
                            {% endfor %}
                        </ul>
                    </p>
                </div>
            </div>                
        </div>
    </div>    

{% endblock content %}

templates/personas/habilidades.html
<h1>Lista de las habilidades de un empleado</h1>


<h3>Lista resultado</h3>
	{% for empleado in habilidades %}
	
		<li> {{ empleado }} </li>
	
	{% endfor %}
	
</ul>

templates/personas/list_all.html
{% extends 'base.html' %}



{% block content %}

{% include 'includes/header.html' %}	

<div class="grid-container">
	<div class="grid-x">
		<h1 class="cell">Lista de los empleados</h1>
		<form class="cell grid-x grid-margin-x" method="GET"> {% csrf_token %}
			<div class="cell large-7">
				<input type="text" id="kword" name="kword" placeholder="Introduzca el empleado a buscar">
			</div>
			<div class="cell large-2">
				<button type="submit" class="success button">Buscar</button>
			</div>
		</form>
		<div class="cell">
			<table>
				<thead>
				  <tr>
					<th width="200">ID</th>
					<th>NOMBRE</th>
					<th width="150">APELLIDOS</th>
					<th width="150">DEPARTAMENTO</th>
					<th width="50">ACCI&Oacute;N</th>
					<th width="50"></th>
					<th width="50"></th>
				  </tr>
				</thead>
				<tbody>
					{% for empleado in empleados %}

						<tr>
							<td>{{ empleado.id }}</td>
							<td>{{ empleado.firstName }}</td>
							<td>{{ empleado.lastName }}</td>
							<td>{{ empleado.departamento.shortName }}</td>
							<td><a class="button warning" href="{% url 'persona_app:empleado_detalle' empleado.id %}">Ver</a></td>
							<td><a class="button warning" href="{% url 'persona_app:modificar_empleado' empleado.id %}">Editar</a></td>
							<td><a class="button alert" href="{% url 'persona_app:borrar_empleado' empleado.id %}">Eliminar</a></td>
						</tr>

					{% endfor %}					
				</tbody>
			  </table>			
			<ul>

			</ul>
		
		</div>
	</div>
	
	<div class="cell">
		
		{% if is_paginated %}
			<nav aria-label="Pagination">
				<ul class="pagination">
					{% if page_obj.has_previous %}
						<li class="pagination-previous">
							<li><a href="?page={{page_obj.previus_page_number}}">Atrás</a></li>
						<span class="show-for-sr">page</span></li>		
					{% endif %}

					
					{% for pagina in paginator.page_range %}
					
						{% if pagina == page_obj.number %} 
							<li class="current"><span class="show-for-sr">You're on page</span>{{pagina}}</li>
						{% else %}
							<li><a href="?page={{pagina}}" aria-label="Page">{{ pagina }}</a></li>
						{% endif %}
						
					{% endfor %}
						
					{% if page_obj.has_next %}
						<li class="pagination-next">
							<li><a href="?page={{page_obj.next_page_number}}" aria-label="Next page">Siguiente</a></li>
						<span class="show-for-sr">page</span></li>		
					{% endif %}				

				</ul>
			</nav>
		{% endif %}
			
	</div>
	
</div>
{% endblock content %}

templates/personas/persona_by_kword.html
<h1>Lista de los empleados por palabra clave</h1>

<form method="GET">{% csrf_token %}
	<input type="text" id="kword" name="kword" placeholder="Introduzca el texto...">
	<button type="submit">Buscar</button>	
</form>
<ul>

<h3>Lista resultado</h3>
	{% for empleado in empleados %}
	
		<li> {{ empleado }}  <form action='../listar_habilidades_e/' method="GET">
			<button type="submit" name="idEmpleado" value="{{ empleado.id }}">Ver habilidades</button>	
		</form></li>
	
	{% endfor %}
	
</ul>

templates/personas/success.html
<h4>Todo correcto</h4>

templates/personas/unsuccess.html
<h4>Fallo</h4>

templates/personas/update.html
{% extends 'base.html' %}

{% block title %}Modificar Empleado{% endblock title %}

    
{% block content %}
    {% include 'includes/header.html' %}

	<div class="grid-container">
		<div class="grid-x">
			<h1 class="cell">Modificar Empleado</h1>

			<div class="cell">
			<form method='POST' class="grid-x"> {% csrf_token %} 
				<div class="cell large-6">
					<label>
						{{ form.as_p }}
					</label>
				</div>
				</div>
					<button class="button success" type ="submit">Guardar Cambios</button>
				</div>
			</form>
			</div>
		</div>
	</div>

{% endblock content %}